default['openvas']['gpg']['key']['type'] = "RSA"
default['openvas']['gpg']['key']['length'] = "2048"
default['openvas']['gpg']['name']['real'] = "Your Organization"
default['openvas']['gpg']['name']['comment'] = "OpenVAS Manager Signing Key"
default['openvas']['gpg']['name']['email'] = "inavlidemail@yourcompany.not"
default['openvas']['gpg']['expire']['date'] = "0"
default['openvas']['gpg']['batch']['config'] = "/tmp/openvas_gpg_batch_config"
